<?php
require('../fpdf/fpdf.php');
require('../php/conexion.php');
$rs = mysql_query("SELECT MAX(asignacion_id) AS id FROM folios_mensualidades");
if ($row = mysql_fetch_row($rs)) {
$id = trim($row[0]);
}
$registro= mysql_query("SELECT fm.asignacion_id, fm.concepto, fm.responsable, fm.total, p.descripcion, p.celular, p.email FROM folios_mensualidades as fm INNER JOIN privadas as p ON fm.privada_id = p.privada_id WHERE fm.asignacion_id = $id");
while($todosLosRegistros= mysql_fetch_array($registro)){
header("Content-Type: text/html;charset=utf-8");
$privada = $todosLosRegistros['descripcion'];
$celular = $todosLosRegistros['celular'];
$email = $todosLosRegistros['email'];
$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetFont('Arial', '', 8);
$pdf->Image('../recursos/videoaccesos.png' , 10 ,10, 60 , 22,'PNG');
$pdf->Cell(10, 10, '', 0);
$pdf->Cell(140, 10, '', 0);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(40, 13, 'FOLIO:', 0,0,'C');
$pdf->Ln(6);
$pdf->Cell(10, 10, '', 0);
$pdf->Cell(140, 10, '', 0);
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(40, 10, 'No. '.$id, 0,0,'C');
$pdf->Ln(6);
$pdf->Cell(10, 10, '', 0);
$pdf->Cell(140, 10, '', 0);
$pdf->SetFont('Arial', 'B', 9);
$pdf->Cell(40, 13, 'FECHA:', 0,0,'C');
$pdf->Ln(5);
$pdf->Cell(10, 10, '', 0);
$pdf->Cell(140, 10, '', 0);
$pdf->SetFont('Arial', '', 9);
$pdf->Cell(40, 10, ''.date('d/m/Y').'', 0,0,'C');
$pdf->Ln(5);
$pdf->SetFont('Arial', 'B', 11);
$pdf->Cell(70, 5, '', 0);
$pdf->Ln(5);
$pdf->SetFont('Arial', '', 10);
	$pdf->Cell(190, 7, utf8_decode('Razón Social: ').$privada, 1,0);
$pdf->Ln(7);
$pdf->Cell(190, 7, utf8_decode('Responsable de Pago: ').$todosLosRegistros['responsable'], 1,0);
	$pdf->Ln(7);
$pdf->Cell(190, 7, utf8_decode('Teléfono Privada: ').$celular, 1,0);
	$pdf->Ln(7);
$pdf->Cell(190, 7, utf8_decode('Correo Electrónico Privada: ').$email, 1,0);
	$pdf->Ln(7);
$pdf->Ln(5);
$pdf->SetFont('Arial', 'B', 9);
$pdf->Cell(30, 6, 'CANTIDAD', 1,0,'C');
$pdf->Cell(100, 6, utf8_decode('CONCEPTO'), 1,0,'C');
$pdf->Cell(30, 6, 'PRECIO UNITARIO', 1,0,'C');
$pdf->Cell(30, 6, 'IMPORTE', 1,0,'C');
$pdf->Ln(6);
$pdf->SetFont('Arial', 'B', 9);
$pdf->Cell(30, 6, '1', 1,0,'C');
$pdf->SetFont('Arial', 'B', 7);
$pdf->Cell(100, 6, $todosLosRegistros['concepto'], 1,0,'C');
$pdf->SetFont('Arial', 'B', 9);
$pdf->Cell(30, 6, '$'.$cuota.'', 1,0,'C');
$pdf->Cell(30, 6, '$'.$cuota.'', 1,0,'C');
$pdf->Ln(6);
$pdf->SetFont('Arial', '', 8);
$pdf->Cell(30, 6, 'Importe con letra: ', 0,0,'L');
$pdf->SetFont('Arial', 'B', 9);
$pdf->Cell(30, 6, '',0,0,'C');
$pdf->Cell(100, 6, 'SubTotal:', 0,0,'R');
$pdf->Cell(30, 6, '$'.$cuota.'',1,0,'C');
$pdf->Ln(6);

$pdf->SetFont('Arial', 'B', 8);
$pdf->Cell(30, 6, '',0,0,'R');
$pdf->Cell(100, 6, 'Son: '.$cantidadLetra.'',0,0,'C');
$pdf->Cell(30, 6, '16 % I.V.A:', 0,0,'R');
$pdf->Cell(30, 6, '$0',1,0,'C');
$pdf->Ln(6);

$pdf->Cell(30, 6, '', 0,0,'C');
$pdf->SetFont('Arial', 'B', 9);
$pdf->Cell(30, 6, '',0,0,'C');
$pdf->Cell(100, 6, 'Total:', 0,0,'R');
$pdf->Cell(30, 6, '$'.$cuota.'',1,0,'C');
$pdf->Ln(6);
$pdf->Cell(30, 6, '', 0,0,'C');
$pdf->SetFont('Arial', 'B', 9);
$pdf->Cell(100, 6, 'www.videoaccesos.com', 1,0,'C');
$pdf->Cell(30, 6, '',0,0,'C');
$pdf->Cell(30, 6, '',0,0,'C');
$pdf->Ln(16);
$pdf->SetFont('Arial', 'U', 8);
$pdf->Cell(160, 5, utf8_decode('                                                                                                              '),0,0,'C');
$pdf->Ln(4);
$pdf->SetFont('Arial', 'B', 8);
$pdf->Cell(160, 5, utf8_decode('FIRMA'),0,0,'C');
$pdf->Ln(15);
}
$pdf->SetFont('Arial', 'B', 8);
$pdf->Cell(114,8,'',0);
$pdf->Output();
?>
