<?php
require('../fpdf/fpdf.php');
require('../php/conexion.php');

$folio=$_POST['txtFolioVenta'];
$paciente=$_POST['txtPacienteVenta'];
$articulo1=$_POST['txtArticulo1'];
$articulo2=$_POST['txtArticulo2'];
$articulo3=$_POST['txtArticulo3'];
$articulo4=$_POST['txtArticulo4'];
$articulo5=$_POST['txtArticulo5'];
$cantidad1=$_POST['txtCantidad1'];
$cantidad2=$_POST['txtCantidad2'];
$cantidad3=$_POST['txtCantidad3'];
$cantidad4=$_POST['txtCantidad4'];
$cantidad5=$_POST['txtCantidad5'];
$precio1=$_POST['txtPrecio1'];
$precio2=$_POST['txtPrecio2'];
$precio3=$_POST['txtPrecio3'];
$precio4=$_POST['txtPrecio4'];
$precio5=$_POST['txtPrecio5'];
$importe1=$_POST['txtImporte1'];
$importe2=$_POST['txtImporte2'];
$importe3=$_POST['txtImporte3'];
$importe4=$_POST['txtImporte4'];
$importe5=$_POST['txtImporte5'];
$descuento=$_POST['txtDescuento'];
$efectivo=$_POST['txtEfectivo'];
$tarjeta=$_POST['txtTarjeta'];
$total=$_POST['txtTotal'];
$pagarCon=$_POST['txtPagarCon'];
$cambio=$_POST['txtCambio'];

$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetFont('Arial', '', 8);
$pdf->Image('../../appDentista/img/logoOrthoclinikG.png' , 10 ,10, 190 , 50,'PNG');
$pdf->Ln(60);
$pdf->SetFont('Arial', '', 10);
	$pdf->Cell(190, 7, utf8_decode('Paciente: ').$paciente, 1,0);
$pdf->Ln(7);
$pdf->SetFont('Arial', 'B', 7);
$pdf->Cell(30, 6, 'CANTIDAD', 1,0,'C');
$pdf->Cell(80, 6, utf8_decode('DESCRIPCION'), 1,0,'C');
$pdf->Cell(40, 6, 'PRECIO UNITARIO', 1,0,'C');
$pdf->Cell(40, 6, 'IMPORTE', 1,0,'C');
$pdf->Ln(6);
$pdf->Cell(30, 6, $cantidad1, 1,0,'C');
$pdf->Cell(80, 6, $articulo1, 1,0,'C');
$pdf->Cell(40, 6, '$'.$precio1, 1,0,'C');
$pdf->Cell(40, 6, '$'.$importe1, 1,0,'C');
$pdf->Ln(6);
$pdf->Cell(30, 6, $cantidad2, 1,0,'C');
$pdf->Cell(80, 6, $articulo2, 1,0,'C');
$pdf->Cell(40, 6, '$'.$precio2, 1,0,'C');
$pdf->Cell(40, 6, '$'.$importe2, 1,0,'C');
$pdf->Ln(6);
$pdf->Cell(30, 6, $cantidad3, 1,0,'C');
$pdf->Cell(80, 6, $articulo3, 1,0,'C');
$pdf->Cell(40, 6, '$'.$precio3, 1,0,'C');
$pdf->Cell(40, 6, '$'.$importe3, 1,0,'C');
$pdf->Ln(6);
$pdf->Cell(30, 6, $cantidad4, 1,0,'C');
$pdf->Cell(80, 6, $articulo4, 1,0,'C');
$pdf->Cell(40, 6, '$'.$precio4, 1,0,'C');
$pdf->Cell(40, 6, '$'.$importe4, 1,0,'C');
$pdf->Ln(6);
$pdf->Cell(30, 6, $cantidad5, 1,0,'C');
$pdf->Cell(80, 6, $articulo5, 1,0,'C');
$pdf->Cell(40, 6, '$'.$precio5, 1,0,'C');
$pdf->Cell(40, 6, '$'.$importe5, 1,0,'C');
$pdf->Ln(6);

$subTotal=$importe1+$importe2+$importe3+$importe4+$importe5;
$total = ($importe1+$importe2+$importe3+$importe4+$importe5) - $descuento;

$pdf->Cell(30, 6, '', 0,0,'C');
$pdf->SetFont('Arial', 'B', 9);
$pdf->Cell(80, 6, '',0,0,'C');
$pdf->Cell(40, 6, 'SubTotal:', 0,0,'R');
$pdf->Cell(40, 6, '$'.$subTotal.'',1,0,'C');
$pdf->Ln(6);
$pdf->Cell(30, 6, '', 0,0,'C');
$pdf->SetFont('Arial', 'B', 9);
$pdf->Cell(80, 6, '',0,0,'C');
$pdf->Cell(40, 6, 'Descuento (-):', 0,0,'R');
$pdf->Cell(40, 6, '$'.$descuento.'',1,0,'C');
$pdf->Ln(6);
$pdf->Cell(30, 6, '', 0,0,'C');
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(80, 6, '',0,0,'C');
$pdf->Cell(40, 6, 'Total:', 0,0,'R');
$pdf->Cell(40, 6, '$'.$total.'',1,0,'C');
$pdf->Ln(15);
$pdf->Cell(30, 6, '', 0,0,'C');
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(80, 6, '',0,0,'C');
$pdf->Cell(40, 6, 'Efectivo:', 0,0,'R');
$pdf->Cell(40, 6, '$'.$efectivo.'',1,0,'C');
$pdf->Ln(6);
$pdf->Cell(30, 6, '', 0,0,'C');
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(80, 6, '',0,0,'C');
$pdf->Cell(40, 6, 'Tarjeta:', 0,0,'R');
$pdf->Cell(40, 6, '$'.$tarjeta.'',1,0,'C');
$pdf->Ln(6);
$pdf->Cell(30, 6, '', 0,0,'C');
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(80, 6, '',0,0,'C');
$pdf->Cell(40, 6, 'Paga con:', 0,0,'R');
$pdf->Cell(40, 6, '$'.$pagaCon.'',1,0,'C');
$pdf->Ln(6);
$pdf->Cell(30, 6, '', 0,0,'C');
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(80, 6, '',0,0,'C');
$pdf->Cell(40, 6, 'Cambio:', 0,0,'R');
$pdf->Cell(40, 6, '$'.$cambio.'',1,0,'C');
$pdf->Ln(6);
$pdf->SetFont('Arial', 'B', 8);
$pdf->Cell(114,8,'',0);
$pdf->Output();
?>